name: On Website Deploy
"on":
  push:
    # (1)
    branches:
      - "master"
jobs:
  build_and_deploy_web:
    name: Build & Deploy Flutter to Web
    runs-on: ubuntu-latest
    # (2)
    steps:
      - uses: actions/checkout@v2
      # (3)
      - name: Make copy of artifacts
        run: |
          chmod u+x "${{ github.workspace }}/createandcopytofolder.sh"
          bash "${{ github.workspace }}/createandcopytofolder.sh"


